image: docker:22.06-rc

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - docker info

stages:
    - build
    - lint
    - push

build:
    stage: build
    tags:
        - x86
    only:
        refs:
            - merge_requests
    script:
        - docker build .

lint:
    stage: lint
    allow_failure: true
    tags:
        - x86
    only:
        refs:
            - merge_requests
    script:
        - docker build --target lint -t "firmware-lint-$CI_COMMIT_SHORT_SHA" .
        - docker run "firmware-lint-$CI_COMMIT_SHORT_SHA"

push:
    stage: push
    tags:
        - x86
    only:
        refs:
            - main
    variables:
        IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"
    script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        - docker build --target build --target load -t "$IMAGE_NAME" .
        - docker push "$IMAGE_NAME"
